
export const secOne = {
    id: 'rent',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Renting",
    headline: "Renting trailers with TrailerHub",
    description: "Search for trailers based on your job or trip requirements. You can choose from a large variety of trailers - we host anything from cargo trailers to boat trailers. Filter your search results by body type, weight rating, coupling type, and many other trailer specifications. Once you've found the right one, choose a pick up and drop off date that works for you and instantly rent the trailer!",
    buttonLabel: 'Hosting',
    imgStart: false,
    img: "/images/trailer_rent_page.png",
    alt: 'TrailerHub Trailer Summary Page',
    dark: true,
    primary: true, 
    darkText: false ,
    linkButton: false,
    buttonLinkTo: 'host',
    appLinks: true,
}

export const secTwo = {
    id: 'host',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Hosting',
    headline: 'Hosting your trailers on TrailerHub',
    description: "Make a profit on your underused asset by renting out your trailer on TrailerHub. Get instant deposits after the trailer rentals are finalized. You choose the daily rate, availability, and pickup/drop-off location. Using our in-app messaging service you can stay in contact with renters 24/7. TrailerHub verifies the renters identity, email, phone number, and payment information. We don't currently provide insurance for your trailer, although we are working hard to make that available in the near future.",
    buttonLabel: 'Business Hosting',
    imgStart: true,
    img: "/images/host_page.png",
    alt: 'TrailerHub Host Page',
    dark: false,
    primary: true,
    darkText: true,
    linkButton: false,
    buttonLinkTo: 'business',
    appLinks: true,
}

export const secThree = {
    id: 'business',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Business Hosting",
    headline: 'Hosting your company\'s trailers on TrailerHub',
    description: 'Get extra leads by non exclusively renting out your trailers on TrailerHub at no cost to you - just add our 10% fee to your regular price. You decide the the daily rate, availability, and pickup/drop-off location. We also keep track of all of your trailer rental records, so that you don\'t have to. If you have a lot of trailers you’d like to upload you don’t need to add them one by one, just contact our support team and we can help get you set up.',
    buttonLabel: 'See more',
    imgStart: false,
    img: "/images/host_rental_record.png",
    alt: 'TrailerHub Rental Record',
    dark: true,
    primary: true,
    darkText: false,
    appLinks: true,
}
